
version: '2'

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:6.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  redis:
    image: redis
    ports:
      - 6379:6379

  redis-cli:
    depends_on:
      - redis
    image: redis
    network_mode: host
    command: redis-cli -h 127.0.0.1 ping


